/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./App.jsx",
    "./main.jsx",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e0e8fc",
        "on-secondary-fixed": "#254800",
        "tertiary-fixed-dim": "#d9e5e8",
        "on-surface-variant": "#a3abbd",
        "surface-dim": "#060e1b",
        "primary-container": "#21fcca",
        "inverse-surface": "#f9f9ff",
        "primary-dim": "#00eabb",
        "on-secondary": "#325c00",
        "surface-variant": "#1a2639",
        "secondary": "#9ffa43",
        "on-secondary-container": "#eaffcf",
        "background": "#060e1b",
        "secondary-container": "#3a6a00",
        "on-secondary-fixed-variant": "#386700",
        "surface-tint": "#a8ffe1",
        "secondary-fixed": "#9ffa43",
        "tertiary-container": "#e1edf1",
        "primary-fixed": "#17f9c8",
        "surface-container-highest": "#1a2639",
        "on-primary-fixed-variant": "#00644f",
        "on-error-container": "#ffa8a3",
        "tertiary-dim": "#d9e5e8",
        "error-container": "#9f0519",
        "primary": "#a8ffe1",
        "primary-fixed-dim": "#00eabb",
        "surface-container": "#0f1a2a",
        "on-primary-container": "#005b47",
        "surface-container-high": "#152031",
        "surface": "#060e1b",
        "tertiary": "#f0fbff",
        "secondary-dim": "#91ec34",
        "on-background": "#e0e8fc",
        "surface-container-low": "#0a1422",
        "surface-container-lowest": "#000000",
        "error-dim": "#d7383b",
        "outline": "#6d7686",
        "on-primary-fixed": "#004535",
        "on-primary": "#00654f",
        "secondary-fixed-dim": "#91ec34",
        "surface-bright": "#1f2c41",
        "on-tertiary-fixed-variant": "#5b666a",
        "outline-variant": "#404857",
        "on-tertiary-fixed": "#3f4a4d",
        "inverse-on-surface": "#4d5565",
        "error": "#ff716c",
        "on-tertiary-container": "#4d595c",
        "on-tertiary": "#556164",
        "inverse-primary": "#006c55",
        "on-error": "#490006",
        "tertiary-fixed": "#e7f3f7"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
